services:
  - type: web
    name: getdigitalsign
    env: python
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVarGroups:
      - name: getdigitalsign-credentials
        envVars:
          - key: SECRET_KEY
            generateValue: true
          - key: GMAIL_USER
            value: ""
          - key: GMAIL_APP_PASSWORD
            value: ""
          - key: SENDGRID_API_KEY
            value: ""
          - key: GOOGLE_CREDENTIALS_JSON
            value: ""
          - key: RECEIVER_EMAIL
            value: ""
